### create an order in order-service
POST http://localhost:8080/api/v1/orders
Content-Type: application/json

{
  "name": "laptop order",
  "qty": 1,
  "price": 10000
}

### create an order in order-service
POST http://localhost:8080/api/v1/orders
Content-Type: application/json

{
  "name": "Book order",
  "qty": 2,
  "price": 12000
}
